### ISSUE TITLE
Update functions that use the NCEAS/RT package 

### ISSUE THREAD

**Issue by dmullen17** [NCEAS/awards-bot#25]
Bryce is re-writing a bunch of the `NCEAS/rt` functions.

**Comment by laijasmine** [comment]
- [x] update the function `create_ticket` (specifically the helper function `check_rt_reply`) to handle the new way `rt_ticket_history_reply` returns errors (it now uses `stopforstatus` to check for the error code)
- [x] update the corresponding `create_ticket` test(s)
