### ISSUE TITLE
Notify of correspondences via email and Slack

### ISSUE THREAD

**Issue by dmullen17** [NCEAS/awards-bot#29]
This particular code likely won't be added to this repository, but I'm creating this issue so I don't forget.  Set up a bot similar to the submissions bot that notifies the members of #awardsbot on correspondences.

**Comment by mbjones** [comment]
Given that the submissions bot is already interacting with RT, I think it would make the most sense to modify it and have it check the additional RT queue, rather than setting up a separate bot.

**Comment by jagoldstein** [comment]
But if possible, we definitely would prefer to have these notifications about replies to award fulfillment emails segregated from notifications about updates, submissions, and other emails to support@arcticdata.io which come to the #arcticbot channel in Slack.

**Comment by mbjones** [comment]
Yeah, the bot could send to different places.  But only one bot is needed to sort through the incoming RT queues.

**Comment by dmullen17** [comment]
Sounds good to me

**Comment by dmullen17** [comment]
Starting to work on this now.  I'm not sure it makes sense for the submissions bot to check the arcticAwards queue.  The awards bot also interacts with RT by creating tickets - so it shouldn't be difficult for it to check for correspondences. 

The downside is the awards bot runs once every 24 hours while the submissions bot runs once every 5 minutes.

**Comment by dmullen17** [comment]
Discussed this on the ADC call.  Modifying the submissions-bot to check the additional queue is actually fairly difficult given how the functions are written (accessing system variables rather than using arguments).  We came to a consensus that keeping the code separate and releasing a minor update (1.1.0) of the awards bot that checks the RT queue makes sense.

**Comment by jagoldstein** [comment]
In addition to notifying us in Slack, these messages should also come to our nceas.ucsb.edu email addresses.

**Comment by jagoldstein** [comment]
Thomas set us up to receive emails, so we are closing this issue for now.
