### ISSUE TITLE
change default branch from master to main

### ISSUE THREAD

**Issue by laijasmine** [NCEAS/awards-bot#32]
@csjx do you have the permissions in this repo to update that? (I don't have the permissions to access the settings needed to make the change)

**Comment by csjx** [comment]
Hi @laijasmine, I'm not sure, but I'll have a look.

**Comment by csjx** [comment]
I don't Jasmine, I think @mbjones will have to change it.

**Comment by laijasmine** [comment]
it's been changed @csjx - sorry didn't update this thread earlier
