### ISSUE TITLE
How far back should the initial bot send emails? 

### ISSUE THREAD

**Issue by dmullen17** [NCEAS/awards-bot#9]
How far back in time should we go for the initial round of NSF award correspondences?  For instance we can look for all awards < 2 years old and send initial correspondence emails.  Or we could look for all non-expired awards and set up some email conditions, for instance:  
- for all awards < 1 year old send an initial correspondence + annual report email 
- for all awards > 1 year old send annual report due date email and no initial correspondence email

Once the bot is up and running it will take care of new awards by itself, but we need to decide how to handle contacting existing NSF awards so as not to inundate them with emails at once.

**Comment by mbjones** [comment]
Be sure to only send emails to awards with the active flag set, and not to
closed ones.

Matt

**Comment by dmullen17** [comment]
@mbjones the bot has that logic.  So you'd like us to contact all active NSF awards regardless of how far back they started?  We can discuss more on the ADC friday call as well - it's on the agenda.

**Comment by jagoldstein** [comment]
If an award is passed its `expDate` according to www.research.gov/common/webapi/awardapisearch-v1.htm we consider it "closed". Otherwise, we assume it is "active". Please correct us if this logic is flawed or needs refinement. 

Which emails should we send @mbjones ? Have you sent the drafts to NSF yet? Two weeks ago, you said this was a priority for NSF and to hurry to prepare the email language so it could be approved by them.

**Comment by jagoldstein** [comment]
https://github.com/NCEAS/awards-bot/issues/6

**Comment by dmullen17** [comment]
More information: 
There are currently 405 active awards.  42 are already documented in the ADC - probably don't need to contact these initially. 

Of the remaining 363 awards 49 have less than 3 months to go before the award expires.  We should contact these with a reminder. 

Of the remaining 314 here's a little information: 190 started in the past 2 years, 122 within the past 1.5 years, and 106 within the past year.

**Comment by dmullen17** [comment]
Contact proposal: 

*General contact:*
- Send an initial congratulatory email at the start of each award, also highlights what is expected of them.
- Send a reminder to submit the first annual report 8 months after the start of the award, along with a recurring reminder each subsequent year
- Send a reminder to submit AON data 11 months after the start of the award, along with a recurring reminder every 6 months afterward

*Initial contact for already active awards:* 
- There are 491 active Arctic NSF awards.  
- Of these 44 are already referenced in the Arctic Data Center - we will not contact these immediately.  
- Of the remaining awards 30 expire on July 31st - contact these with a reminder that their award is expiring soon.  
- Of the remaining awards 138 started within the past year - contact these with the initial congratulatory email outlining what is expected of them.  

This contains a summary of the active awards along with flags if they have one month remaining, started within the past year, or are already documented.
[active_awards.xlsx](https://github.com/NCEAS/awards-bot/files/2247263/active_awards.xlsx)
